services:
  db:
    container_name: prod_db
    image: postgres:15-alpine
    volumes:
      - prod_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env

  pgadmin:
    container_name: prod_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
       - .env

  app:
    container_name: prod_app
    build:
      context: .
      target: production 
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app         
    command: /bin/sh -c "npm run migration:run && npm run start:prod"

volumes:
  prod_data:
