services:
  db:
    container_name: prod_db
    image: postgres:15-alpine
    volumes:
      - prod_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env.production
    restart: always

  pgadmin:
    container_name: prod_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
       - .env.production

  redis:
    container_name: prod_redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
    env_file:
      - .env.production 
    restart: always

  app:
    container_name: prod_app
    build:  
      context: .
      target: production 
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    env_file:
      - .env.production      
    command: /bin/sh -c "npx drizzle-kit migrate --config=/app/dist/drizzle.config.js && node dist/src/main" 
    restart: always


volumes:
  prod_data:
  redis_volume_data:
