services:
  db:
    container_name: dev_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    restart: always

  pgadmin:
    container_name: dev_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  redis:
    container_name: dev_redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
    restart: always

volumes:
  postgres_data:
  redis_volume_data:
