services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
    - .env

volumes:
  postgres_data:  