@baseUrl =  http://localhost:3000/api/v1

### Create an Account
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "email":"email@example.com",
    "username":"helloworld",
    "password":"12345678",
    "phoneNumber":"+21354454545"
}

### Login an Account
# @name loginAuth
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"email@example.com",
    "password":"12345678"
}


### Get the current authed user by accessToken

GET {{baseUrl}}/auth/me
Content-Type: application/json
Authorization: Bearer {{loginAuth.response.body.$.accessToken}}
